@startuml


Actor interfazUsuario as usuario

participant ":Juego" as Juego
participant ":FaseConstruccion" as builder
participant ":Enemigos" as enemies
participant ":EstructurasActivas" as estr
participant ":SistemaConstrucicon" as constr

usuario-> Juego: haySiguienteTurno(ui)
activate Juego
Juego -> builder: hacerTurno(ui,jugador)
activate builder


builder--> Juego: void
deactivate builder

Juego->enemies: puedeMatar(jugador)
activate enemies
enemies--> Juego: true
deactivate enemies

Juego->enemies: accionar(ui,mapa,jugador)
activate enemies
enemies--> Juego: void
deactivate enemies


Juego->constr: accionar(ui,mapa,jugador)
activate constr
constr--> Juego: void
deactivate constr

Juego->estr: accionar(ui,mapa,jugador)
activate estr
estr--> Juego: void
deactivate estr



Juego->enemies: verificarQuedanEnemigos()
activate enemies
enemies--> Juego: true
deactivate enemies


Juego --> usuario: (sigue el nivel?) True
deactivate Juego


@enduml