@startuml

interface Actor{
    +accionarEn(turno, controladorJuego)
}

class FaseConstruccion{
    +accionarEn(turno, controladorJuego)
    -mostrarUsuarioConstrucciones()
}

class Enemigos{
    +accionarEn(turno, controladorJuego)
}

class DefensasJugador{
    +accionarEn(mapa:Mapa,jugador)
}

FaseConstruccion ....|> Actor
DefensasJugador ....|> Actor
Enemigos ....|> Actor


@enduml