@startuml

class Oleada{

}


class Enemigos{
    Enemigos(oleadas, gestorObjetos)
    + accionarEn(turno, controlador)
    + atacarMasCercano(posicion,defensa)
}

interface Unidad{
    + isAlive() bool
    + recibirAtaque(dmg)
    + moverseEn(mapa)
}



class Enemigo{
    + isAlive() bool
    + recibirAtaque(dmg)
    + accionEn(gestorObjetos, controladorJuego) bool
}

interface GameEntity
Unidad...|> GameEntity

Enemigos --> Enemigo
Enemigo ..|> Unidad
Enemigos --> Oleada

@enduml