@startuml

interface ControladorJuego{

}

class Juego{
}



interface Actor{
    +accionarEn(turno, juego)
}

class Jugador{
}



class Enemigos{
    +accionarEn(turno, juego)
}

class DefensasJugador{
    +accionarEn(turno, juego)
}

class FaseConstruccion{
    +accionarEn(turno, juego)
}

interface GestorObjetos

class Mapa{
}

class GestorTurnos{
}


class ControladorBase{
}

ControladorBase --> Jugador
Mapa ...|> GestorObjetos
ControladorBase --> GestorObjetos

ControladorBase --> Enemigos
ControladorBase ..|> ControladorJuego

Juego --> GestorTurnos
Juego-->ControladorBase

GestorTurnos ..> ControladorJuego
GestorTurnos --> Actor

Enemigos ..|> Actor
DefensasJugador ..|> Actor
FaseConstruccion ..|> Actor




@enduml