@startuml

Actor alguien as sis

participant ":Mapa" as mapa
participant ":Camino" as camino
participant ":Pasarela" as pasarela

sis-> mapa: obtenerMasCercanoFinal(posicion,rangoMaximo)
activate mapa

mapa->camino: obtenerPasarela\nEnRango(posicion,rango)
activate camino
camino-->mapa: pasarela
deactivate camino

mapa-> mapa: verificarNoSeaNull

mapa->pasarela: obtener()
activate pasarela
pasarela--> mapa: arr[unidades]
deactivate pasarela

mapa--> sis: arr[unidades]
deactivate mapa

@enduml