@startuml

Actor interfazUsuario as sis

sis-> Construible: iniciarConstruccion()

note left
siempre interfazUsuario entre cada mensaje
a Construible le pidio a usuario o test
una accion, mocking para tests.
Capaz tambien se podria cancelar?
end note

Construible -> ConstruccionTentativa: ConstruccionTentativa(construcciones, construccion)
ConstruccionTentativa->  Construible: construccionTentativa

Construible-> sis:construcctionTentativa

sis->sis: simularPosicionamiento\n(construccion)

group simulacion
group Falla

sis -> ConstruccionTentativa: construir()
ConstruccionTentativa-> sis: False
sis-> sis : mostrarErrorUsuario()
end group


group mover?
sis -> ConstruccionTentativa : moverCentroA(posicion)
sis -> ConstruccionTentativa : moverCentroA(posicion2)
end group

group Finalizar
sis -> ConstruccionTentativa: construir()
ConstruccionTentativa-> sis: True
end group
end group


@enduml