@startuml


Actor interfazUsuario as usuario

usuario -> PantallaOut: EmpezarPartida()

loop manejoTurnos? mientras haySiguienteTurno == True


note right 
el como lo haga no es importante, 
pero le dira empezar la partida.....
ahora PantallaOut ya no inicia un juego, dice jugarTurno.
Sacando la logica de manejo de turnos 
fuera de Juego escencialmente
end note



PantallaOut-> Juego: haySiguienteTurno(this)

Juego -> FaseConstruccion: hacerTurno(pantalla,otrosParametros?)

note right
podria ser, y yo lo haria,
de poner un gestor de turnos en el medio
end note


FaseConstruccion-> Juego: void
Juego -> Juego: haceRestoDelTurno()
Juego -> PantallaOut: (sigue el juego?) True
end
@enduml